#ifndef SERVER_SHERK_SERVICE_MECHANISM_INCLUDE_DEFINE_CONST_H
#define SERVER_SHERK_SERVICE_MECHANISM_INCLUDE_DEFINE_CONST_H

// 常量定义


// 传输的SQL最大长度和接收服务端响应的缓冲区长度
#define CONST_BUFFER_SIZE 100000
#define CONST_RESPONSE_SIZE 100000

#endif