#ifndef SERVER_INCLUDE_DEFINE_CONST_H
#define SERVER_INCLUDE_DEFINE_CONST_H

// 常量定义

#define CONST_NAME_MIN_LEN 5
#define CONST_NAME_MAX_LEN 20
#define CONST_PASSWORD_MIN_LEN 5
#define CONST_PASSWORD_MAX_LEN 20

#endif